version: "3.8"

services:
  web:
    build: .
    command: >
      bash -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rails s -b 0.0.0.0 -p 3000
      "
    ports:
      - "3000:3000"
    depends_on:
      - meilisearch
    environment:
      RAILS_ENV: development
      MEILISEARCH_URL: "http://meilisearch:7700"
      MEILISEARCH_API_KEY: "SUPERSECRET"
    volumes:
      - .:/app:delegated
      - bundle_cache:/usr/local/bundle
      - db_data:/app/storage # <-- для SQLite хранилища!
      - /app/tmp
      - /app/node_modules

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "SUPERSECRET"

volumes:
  bundle_cache:
  db_data: # <-- том для базы данных!
