version: "3.8"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      meilisearch:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      MEILISEARCH_URL: "http://meilisearch:7700"
      MEILISEARCH_API_KEY: "aUqdDnTZ5sq9uVqLZLC6bGVcbOYI0bHbkR4zytR1zR8"
    volumes:
      - .:/app:delegated
      - ./db:/app/db
      - bundle_cache:/usr/local/bundle
      - /app/tmp
      - /app/node_modules

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "aUqdDnTZ5sq9uVqLZLC6bGVcbOYI0bHbkR4zytR1zR8"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  bundle_cache:
