version: "3.8"

services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - meilisearch
    environment:
      RAILS_ENV: development
      MEILISEARCH_URL: "http://meilisearch:7700"
      MEILISEARCH_API_KEY: "SUPERSECRET"
    volumes:
      - .:/app:delegated
      - ./db:/app/db # <-- монтируем локальную папку db внутрь контейнера
      - bundle_cache:/usr/local/bundle
      - /app/tmp
      - /app/node_modules

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "SUPERSECRET"

volumes:
  bundle_cache:
