services:
  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - meilisearch
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app:delegated
  #     - bundle_cache:/usr/local/bundle
  #     - /app/tmp
  #     - /app/node_modules

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: your_secret_key

volumes:
  bundle_cache:
