version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: "masterKey"
    ports:
      - "7700:7700"

  app:
    build: ./app
    depends_on:
      - meilisearch
    environment:
      MEILI_MASTER_KEY: "masterKey"
    volumes:
      - ./app:/usr/src/app
